print   ("Content-type:text/html\r\n\r\n")
print   ("<html>")
print   ("<body>")
print   ("<center>")
print   ("<h1>Welcome To Amity's Dashboard</h1><align='center'>")
print   ("<h3><a href=profiledisp.py>View My Profile</h3>")
print   ("</center>")
print   ("</body>")
print   ("</html>")
